# hello world internationalized
GET {{baseUrl}}hello-world-internationalized
Accept-Language: fr

###

# create an user
POST {{baseUrl}}users
Content-Type: application/json

{
  "name": "simone",
  "birthDate": "2000-03-04T01:31:50.026+00:00"
}

###

# retrieve an user with auth on (comment/decomment POM.xml)
GET {{baseUrl}}users/2
Authorization: Basic user f0dd95c8-e85f-4fb0-9808-8216fe08140ak

###

# delete an user
DELETE {{baseUrl}}users/3

###

# get all the users in xml
GET {{baseUrl}}users
Accept: application/xml

###

# filter example
GET {{baseUrl}}filtering

###

# filter-list example
GET {{baseUrl}}filtering-list

###

# versions examples
GET {{baseUrl}}v1/person

###

GET {{baseUrl}}v2/person

###

GET {{baseUrl}}person/param?version=1

###

GET {{baseUrl}}person/param?version=2

###

GET {{baseUrl}}person/header
X-API-VERSION: 1

###

GET {{baseUrl}}person/header
X-API-VERSION: 2

###

GET {{baseUrl}}person/produces
Accept: application/vnd.company.app-v1+json

###

GET {{baseUrl}}person/produces
Accept: application/vnd.company.app-v2+json

###

#jpa
GET {{baseUrl}}jpa/users

###

GET {{baseUrl}}jpa/users/1

