# hello world internationalized
GET {{baseUrl}}hello-world-internationalized
Accept-Language: fr

###

# create an user
POST {{baseUrl}}users
Content-Type: application/json

{
  "name": "simone",
  "birthDate": "2000-03-04T01:31:50.026+00:00"
}

###

# retrieve an user
GET {{baseUrl}}users/2

###

# delete an user
DELETE {{baseUrl}}users/3

###

# get all the users in xml
GET {{baseUrl}}users
Accept: application/xml

###

# filter example
GET {{baseUrl}}filtering

###

# filter-list example
GET {{baseUrl}}filtering-list

###
